- name: Installs proxysql
  yum:
    name: https://www.percona.com/downloads/proxysql/proxysql-1.4.4/binary/redhat/7/x86_64/proxysql-1.4.4-1.1.el7.x86_64.rpm
    state: present

- name: Installs mysql-common & client
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - mariadb

- name: Configures proxysql
  template:
    src: proxysql.cnf.j2
    dest: /etc/proxysql.cnf
    mode: 0644
    backup: yes
  notify: Restart proxysql

- name: Creates log dir
  file:
    path: /var/log/proxysql/
    state: directory

- name: Adds logrotate
  template:
    src: proxysql.logrotate.conf.j2
    dest: /etc/logrotate.d/proxysql
    mode: 0644

